version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/fed_discord/
hooks:
  AfterInstall:
   - location: install_dependencies.sh
     timeout: 300
     runas: root
  ApplicationStart:
   - location: run.sh
     timeout: 300
     runas: root
     
